#!/bin/bash

docker run --restart=always -d -p 80:80 -e WF_PROXY=$WF_PROXY -e NATS_ENDPOINT=$NATS_ENDPOINT -e WAVEFRONT_INSTANCE=$WAVEFRONT_INSTANCE -e WAVEFRONT_TOKEN=$WAVEFRONT_TOKEN duboc/cdbackend-nats:1.0
